/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.mmmi.mdsd.x21;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Custom Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.x21.CustomType#getDeclaration <em>Declaration</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.x21.X21Package#getCustomType()
 * @model
 * @generated
 */
public interface CustomType extends Type
{
  /**
   * Returns the value of the '<em><b>Declaration</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declaration</em>' reference.
   * @see #setDeclaration(DataDecl)
   * @see dk.sdu.mmmi.mdsd.x21.X21Package#getCustomType_Declaration()
   * @model
   * @generated
   */
  DataDecl getDeclaration();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.x21.CustomType#getDeclaration <em>Declaration</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Declaration</em>' reference.
   * @see #getDeclaration()
   * @generated
   */
  void setDeclaration(DataDecl value);

} // CustomType
