/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.mmmi.mdsd.x21;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.mmmi.mdsd.x21.X21Package#getElement()
 * @model
 * @generated
 */
public interface Element extends EObject
{
} // Element
