/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.mmmi.mdsd.x21;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lambda</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.x21.Lambda#getLogic <em>Logic</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.x21.X21Package#getLambda()
 * @model
 * @generated
 */
public interface Lambda extends NameAndType, FunctionOrLambda, DataRef
{
  /**
   * Returns the value of the '<em><b>Logic</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Logic</em>' containment reference.
   * @see #setLogic(Exp)
   * @see dk.sdu.mmmi.mdsd.x21.X21Package#getLambda_Logic()
   * @model containment="true"
   * @generated
   */
  Exp getLogic();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.x21.Lambda#getLogic <em>Logic</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Logic</em>' containment reference.
   * @see #getLogic()
   * @generated
   */
  void setLogic(Exp value);

} // Lambda
