/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.mmmi.mdsd.x21;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primary</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.mmmi.mdsd.x21.X21Package#getPrimary()
 * @model
 * @generated
 */
public interface Primary extends MulDiv
{
} // Primary
