/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.mmmi.mdsd.x21;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Stream</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.x21.Stream#getStartNodes <em>Start Nodes</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.x21.Stream#getPoints <em>Points</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.x21.X21Package#getStream()
 * @model
 * @generated
 */
public interface Stream extends Declaration
{
  /**
   * Returns the value of the '<em><b>Start Nodes</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.mmmi.mdsd.x21.NodeOrInput}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start Nodes</em>' containment reference list.
   * @see dk.sdu.mmmi.mdsd.x21.X21Package#getStream_StartNodes()
   * @model containment="true"
   * @generated
   */
  EList<NodeOrInput> getStartNodes();

  /**
   * Returns the value of the '<em><b>Points</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.mmmi.mdsd.x21.ElementList}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Points</em>' containment reference list.
   * @see dk.sdu.mmmi.mdsd.x21.X21Package#getStream_Points()
   * @model containment="true"
   * @generated
   */
  EList<ElementList> getPoints();

} // Stream
