/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.mmmi.mdsd.iF22.impl;

import dk.sdu.mmmi.mdsd.iF22.ConcatenationPart;
import dk.sdu.mmmi.mdsd.iF22.IF22Package;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Concatenation Part</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ConcatenationPartImpl extends LessGreaterThanImpl implements ConcatenationPart
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConcatenationPartImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IF22Package.Literals.CONCATENATION_PART;
  }

} //ConcatenationPartImpl
