/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.mmmi.mdsd.iF22.impl;

import dk.sdu.mmmi.mdsd.iF22.GreaterThanOrEquals;
import dk.sdu.mmmi.mdsd.iF22.IF22Package;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Greater Than Or Equals</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class GreaterThanOrEqualsImpl extends LessGreaterThanImpl implements GreaterThanOrEquals
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GreaterThanOrEqualsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IF22Package.Literals.GREATER_THAN_OR_EQUALS;
  }

} //GreaterThanOrEqualsImpl
