/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.mmmi.mdsd.iF22;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>And</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.mmmi.mdsd.iF22.IF22Package#getAnd()
 * @model
 * @generated
 */
public interface And extends BooleanOperation
{
} // And
