/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.mmmi.mdsd.iF22;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ending Target</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.iF22.EndingTarget#getEndStatement <em>End Statement</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.iF22.EndingTarget#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.iF22.IF22Package#getEndingTarget()
 * @model
 * @generated
 */
public interface EndingTarget extends EObject
{
  /**
   * Returns the value of the '<em><b>End Statement</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End Statement</em>' reference.
   * @see #setEndStatement(End)
   * @see dk.sdu.mmmi.mdsd.iF22.IF22Package#getEndingTarget_EndStatement()
   * @model
   * @generated
   */
  End getEndStatement();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.iF22.EndingTarget#getEndStatement <em>End Statement</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End Statement</em>' reference.
   * @see #getEndStatement()
   * @generated
   */
  void setEndStatement(End value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' containment reference.
   * @see #setTarget(Target)
   * @see dk.sdu.mmmi.mdsd.iF22.IF22Package#getEndingTarget_Target()
   * @model containment="true"
   * @generated
   */
  Target getTarget();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.iF22.EndingTarget#getTarget <em>Target</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' containment reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(Target value);

} // EndingTarget
