/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.mmmi.mdsd.iF22;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Greater Than</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.iF22.GreaterThan#getLeft <em>Left</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.iF22.GreaterThan#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.iF22.IF22Package#getGreaterThan()
 * @model
 * @generated
 */
public interface GreaterThan extends LessGreaterThan
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(LessGreaterThan)
   * @see dk.sdu.mmmi.mdsd.iF22.IF22Package#getGreaterThan_Left()
   * @model containment="true"
   * @generated
   */
  LessGreaterThan getLeft();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.iF22.GreaterThan#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(LessGreaterThan value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(ConcatenationPart)
   * @see dk.sdu.mmmi.mdsd.iF22.IF22Package#getGreaterThan_Right()
   * @model containment="true"
   * @generated
   */
  ConcatenationPart getRight();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.iF22.GreaterThan#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(ConcatenationPart value);

} // GreaterThan
