/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.mmmi.mdsd.iF22;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Greater Than Or Equals</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.mmmi.mdsd.iF22.IF22Package#getGreaterThanOrEquals()
 * @model
 * @generated
 */
public interface GreaterThanOrEquals extends LessGreaterThan
{
} // GreaterThanOrEquals
