/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.mmmi.mdsd.iF22;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Target</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.iF22.Target#getDestination <em>Destination</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.iF22.Target#getArguments <em>Arguments</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.iF22.Target#getCondition <em>Condition</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.iF22.Target#getEndTargets <em>End Targets</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.iF22.IF22Package#getTarget()
 * @model
 * @generated
 */
public interface Target extends EObject
{
  /**
   * Returns the value of the '<em><b>Destination</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Destination</em>' reference.
   * @see #setDestination(TargetDestination)
   * @see dk.sdu.mmmi.mdsd.iF22.IF22Package#getTarget_Destination()
   * @model
   * @generated
   */
  TargetDestination getDestination();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.iF22.Target#getDestination <em>Destination</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Destination</em>' reference.
   * @see #getDestination()
   * @generated
   */
  void setDestination(TargetDestination value);

  /**
   * Returns the value of the '<em><b>Arguments</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.mmmi.mdsd.iF22.Exp}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arguments</em>' containment reference list.
   * @see dk.sdu.mmmi.mdsd.iF22.IF22Package#getTarget_Arguments()
   * @model containment="true"
   * @generated
   */
  EList<Exp> getArguments();

  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(Exp)
   * @see dk.sdu.mmmi.mdsd.iF22.IF22Package#getTarget_Condition()
   * @model containment="true"
   * @generated
   */
  Exp getCondition();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.iF22.Target#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(Exp value);

  /**
   * Returns the value of the '<em><b>End Targets</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.mmmi.mdsd.iF22.EndingTarget}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End Targets</em>' containment reference list.
   * @see dk.sdu.mmmi.mdsd.iF22.IF22Package#getTarget_EndTargets()
   * @model containment="true"
   * @generated
   */
  EList<EndingTarget> getEndTargets();

} // Target
