/*
 * generated by Xtext 2.26.0
 */
package dk.sdu.mmmi.mdsd.parser.antlr;

import com.google.inject.Inject;
import dk.sdu.mmmi.mdsd.parser.antlr.internal.InternalX21Parser;
import dk.sdu.mmmi.mdsd.services.X21GrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class X21Parser extends AbstractAntlrParser {

	@Inject
	private X21GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalX21Parser createParser(XtextTokenStream stream) {
		return new InternalX21Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "X21";
	}

	public X21GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(X21GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
