/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.mmmi.mdsd.validation;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class X21Validator extends AbstractX21Validator {
}
